sudo: required
services:
  - docker

before_install:
  - docker build -t wscho/docker-react -f Dockerfile.dev .

script:
  - docker run wscho/docker-react npm run test -- --coverage

depoly:
  provider: elasticbeanstalk
  region: 
